pose_parameters:
  t_pipe_u: {t_vec: [[14], [20], [-155]], t_vec_up: [[14], [20], [-280]], r_vec: [[0], [0], [0]]}
  pipe_u: {t_vec: [[20], [27.5], [-155]], t_vec_up: [[20], [27.5], [-280]], r_vec: [[0], [0], [1.5708]]}
  L_pipe_u: {t_vec: [[60], [40], [-155]], t_vec_up: [[60], [20], [-280]], r_vec: [[0], [0], [0]]}
